FROM python:3.10-slim

#
WORKDIR /code

#
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#
COPY ./project3/test/requirements.txt /code/requirements.txt

#
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

#
COPY ./project3/test/ /code/app

#
CMD ["pytest", "app/test_main.py"]
