version: '3.8'
name: test
services:
  test_app:
    container_name: test_app
    build:
      context: .
      dockerfile: Dockerfile_test
    depends_on:
      web:
        condition: service_healthy
    network_mode: "host"
    command: "pytest app/test_main.py"
    expose:
      - 6379
      - 8000
  web:
    container_name: main_app
    build:
      context: .
      dockerfile: Dockerfile_app
    ports:
      - 8000:8000
    volumes:
      - ./project3/app/:/app/
    env_file:
      - ./.env
    healthcheck:
      test: curl -sS http://127.0.0.1:8000 || echo 1
      interval: 5s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - my-net
  db:
    container_name: db_for_test
    image: "postgres:15.1-alpine"
    env_file:
      - ./.env
    healthcheck:
      test: pg_isready -U postgres -d mydb
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my-net
    expose:
      - 5432
  cashe:
    container_name: cache_db_test
    image: redis
    networks:
      - my-net
    ports:
      - 6379:6379
    expose:
      - 6379

networks:
  my-net:
    name: my-net
