FROM python:3.10-slim

#
WORKDIR /code

#
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#
COPY ./requirements.txt /code/requirements.txt

#
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

#
COPY ./project3/ /code/

#
CMD ["pytest", "app/test_main.py"]
